Use aborting language instead of sorry

diff --git a/.local/bin/pkg b/.local/bin/pkg
--- a/.local/bin/pkg
+++ b/.local/bin/pkg
@@ -12,7 +12,7 @@ if [ -r /etc/os-release ]; then
   # shellcheck disable=SC1091
   OS_DISTRO="$(. /etc/os-release && echo "${ID_LIKE:-${ID}}")"
   if [ "${OS_DISTRO}" != "arch" ]; then
-    echo "This script is only available on Arch Linux, sorry!" >&2
+    echo "This script is only available on Arch Linux, aborting!" >&2
     exit 1
   fi
 fi
diff --git a/.local/bin/rec-start b/.local/bin/rec-start
--- a/.local/bin/rec-start
+++ b/.local/bin/rec-start
@@ -12,7 +12,7 @@ set -o pipefail
 set -o nounset
 
 if [ -z "${NIRI_SOCKET}" ]; then
-  echo "This script is only available with the desktop environment, sorry!" >&2
+  echo "This script is only available with the desktop environment, aborting!" >&2
   exit 1
 fi
 
